version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

