version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-package:
          package-manager: npm
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test

